name: manual workflow
on:
  push:
    branches: [azure-appservice]
  workflow_dispatch:
  repository_dispatch:
    types: [opened, deleted, created]

env:
  AZURE_WEBAPP_NAME: weekdone # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./client" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "10.x" # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Install NPM packages
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: NodeJsScan Scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: "."
      - name: Weekdone Client npm build and Install
        run: |
          npm ci
        working-directory: ./client
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
